matrix:
  include:
    - language: objective-c
      os: osx
      osx_image:
        - xcode8
        - xcode10.2
      cache:
        directories:
          - Carthage
      before_script:
      script:
        - ./script-ios.sh
