matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode11.3
      cache:
        directories:
          - Carthage
      before_script:
      script:
        - ./script-ios.sh
